const songFiles = [
  "song1.mp3",
  "song2.mp3",
  "song3.mp3",
  "song4.mp3",
  "song5.mp3",
  "song6.mp3",
  "song7.mp3",
  "song8.mp3",
  "song9.mp3",
  "song10.mp3",
  "song11.mp3",
  "song12.mp3",
  "song13.mp3",
  "song14.mp3",
  "song15.mp3",
  "song16.mp3",
  "song17.mp3",
  "song18.mp3",
  "song19.mp3",
  "song20.mp3",
  "song21.mp3",
  "song22.mp3",
  "song23.mp3",
  "song24.mp3",
  "song25.mp3",
  "song26.mp3",
  "song27.mp3",
  "song28.mp3",
  "song29.mp3",
  "song30.mp3",
  "song31.mp3",
  "song32.mp3",
  "song33.mp3",
  "song34.mp3",
  "song35.mp3",
];

const songTitles = [
  "Victory Anthem",
  "Jatt Mehkma",
  "Millionaire",
  "Amkhon se batana",
  "Khwaab",
  "Ye Ishq Hai",
  "Girl I need You",
  "Relation",
  "Lehenga",
  "Bulleya",
  "Prem Ki Naiya Hai",
  "Punjabi Wedding",
  "Mitwa",
  "Yaad Piya Ki",
  "Teri Aankhon Mein",
  "Jhol",
  "Aashiq Tera",
  "O Rangrez",
  "Tum Mile",
  "Gandi Baat",
  "Teri Ore",
  "Mat Maari",
  "Tu Hi Mera",
  "One Love",
  "Rang Sharbaton ka",
  "Ye Tune Kya Kiya",
  "Tera Deedar Hua",
  "Ye Tune Kya Kiya - Love Version",
  "Te Amo",
  "Tu jaane na",
  "Pal Pal",
  "Tose naina",
  "Raat Bhar",
  "Zaroor",
  "Tu Na Samjhe"
];

const songImages = [
  "image1.jpg",
  "image2.jpg",
  "image3.jpg",
  "image4.jpg",
  "image5.jpg",
  "image6.jpg",
  "image7.jpg",
  "image8.jpg",
  "image9.jpg",
  "image10.jpg",
  "image11.jpg",
  "image12.jpg",
  "image13.jpg",
  "image14.jpg",
  "image15.jpg",
  "image16.jpg",
  "image17.jpg",
  "image18.jpg",
  "image19.jpg",
  "image20.jpg",
  "image21.jpg",
  "image22.jpg",
  "image23.jpg",
  "image24.jpg",
  "image25.jpg",
  "image26.jpg",
  "image27.jpg",
  "image28.jpg",
  "image29.jpg",
  "image30.jpg",
  "image31.jpg",
  "image32.jpg",
  "image33.jpg",
  "image34.jpg",
  "image35.jpg"
];

const artistNames = [
  "Salim Sulaiman",
  "Karan Aujla",
  "Inder Chahal",
  "Dino James",
  "Akhil",
  "Pritam, Shreya Ghoshal, Arijit Singh",
  "Meet Bros, Arijit Singh",
  "Ninja",
  "Jass Manak",
  "Pritam, Amit Mishra",
  "Shreya Ghoshal, Shaan",
  "Sunidhi Chauhan, Benny Dayal",
  "Shankar-Ehsaan-Loy, Shafqat Amanat Ali",
  "Falguni Pathak",
  "Zara Khan, Dev Negi",
  "Raftaar",
  "Amit Mishra, Aditi Singh Sharma",
  "Shankar Mahadevan, Javed Bashir",
  "Neeraj Shridhar",
  "Vishal Dadlani, Shreya Ghoshal",
  "Arijit Singh, Shreya Ghoshal",
  "Amit Trivedi, Shreya Ghoshal",
  "Pritam",
  "Shubh",
  "Shreya Ghoshal, Arijit Singh",
  "Kailash Kher",
  "Rahat Fateh Ali Khan",
  "Ash King",
  "Arijit Singh",
  "Ali Somro",
  "Arijit Singh",
  "Arjit Singh",
  "Aparshakti",
  "Raja"
];

const songs = songFiles.map((src, i) => ({
  name: songTitles[i],
  artist: artistNames[i],
  cover: `assets/${songImages[i]}`,
  src: `assets/${src}`
}));
